spring.application.name=jwtsecurity

spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}

# Database configuration
spring.datasource.url=jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME};encrypt=true;trustServerCertificate=true;lockTimeout=30;
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Jwts Configuration
app.security.secretKey=${ACCESS_TOKEN_SECRET_KEY}
app.security.accessTokenExpiration=3600000
app.security.refreshTokenExpiration=604800000

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Swagger Configuration
springdoc.api-docs.path=/api-docs

# Server Configuration
server.port=8080

# Frontend Configuration
app.frontend.url=${REACT_APP_URL}
